### ISSUE TITLE
请求失败，错误怎么通过catch 获得

### ISSUE THREAD

**Issue by zcdevgithub** [xCss/JsonBird#1]

**Comment by zcdevgithub** [comment]
我希望能返回错误时的status，可是通过代理status总是200

**Comment by xCss** [comment]
请问是哪个接口呢？
v1代理接口的话，默认是返回`源接口`的`源数据`

**Comment by zcdevgithub** [comment]
是v1 可是错误时返回格式成了这样
![image](https://cloud.githubusercontent.com/assets/26179648/23883195/66fd51ea-08a0-11e7-85a8-8cd51f36122c.png)

**Comment by zcdevgithub** [comment]
能直接已错误状态返回吗

**Comment by xCss** [comment]
很抱歉哦，我检查了下，有两种情况：
- 1. 如果发现代理的目标链接返回正常(不管是正确值还是错误值)，返回code值都是200
- 2. 如果发现代理的目标链接返回不正常(没返回)，返回code值都是 -1，如下图：
![tim 20170314103251](https://cloud.githubusercontent.com/assets/10877162/23883396/9aacca88-08a1-11e7-9e57-f991a104002f.png)

**Comment by zcdevgithub** [comment]
可是这个-1是在data里的能改到外边吗 这里
![image](https://cloud.githubusercontent.com/assets/26179648/23883533/8cc5fd8a-08a2-11e7-87d3-b9dc84a74598.png)

**Comment by xCss** [comment]
看来你是没有理解我上面所说的，请求有3种情况：
1. 代理`源链接正常`，`返回值正常`，返回值内容为`正常值`，这种情况返回200
2. 代理`源链接正常`，`返回值正常`，返回值内容为`错误值`，这种情况返回200 (<=这里应该是你想要的-1的地方)
3. 代理`源链接不正常`，这种情况返回-1

以上3种情况，在前面两种情况中，返回值200代表的是目标`源链接`请求正常，而不是返回值是否正常。

而你的问题是。。。你的截图是ajax框架的返回值，而不是我的v1接口的返回值，v1接口返回值只是你截图里的data。。。
![tim 20170314103251](https://cloud.githubusercontent.com/assets/10877162/23883749/0c63fdf2-08a4-11e7-91df-9e629073386e.png)
