### ISSUE TITLE
歌曲接口：https://bird.ioliu.cn/netease/song?id=222222

### ISSUE THREAD

**Issue by zhaoxieluoke** [xCss/JsonBird#10]
{
data: { },
status: {
code: -1,
msg: "something happend. Please checked your id or url"
}
}

歌单可以获取到,但是歌曲现在又没有返回结果了
又要继续要斗智斗勇了 - _ -

**Comment by xCss** [comment]
@zhaoxieluoke 已修复:smile:，https://bird.ioliu.cn/netease/song?id=222222

**Comment by zhaoxieluoke** [comment]
多谢多谢
