### ISSUE TITLE
打扰了请问jsonBird怎么使用代理跨域post？

### ISSUE THREAD

**Issue by Kevinzhang29** [xCss/JsonBird#11]
谷歌插件，在https网站上post请求给http服务器的数据。请问该怎么使用jsonBird？

**Comment by xCss** [comment]
@Kevinzhang29 抱歉，我也没坐过谷歌插件开发。
不过。。。我觉得貌似不用代理吧，谷歌浏览器本身就是一个代理程序了吧。。。貌似可以直接请求~~~(不太确定)
