### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by chenyanmo** [xCss/JsonBird#12]
/opt/JsonBird
# /usr/bin/npm start

> JsonBird@1.4.0 start /opt/JsonBird
> supervisor node ./bin/www

sh: 1: supervisor: not found

npm ERR! Linux 4.4.13-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.8.1
npm ERR! npm  v2.15.11
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! JsonBird@1.4.0 start: `supervisor node ./bin/www`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the JsonBird@1.4.0 start script 'supervisor node ./bin/www'.
npm ERR! This is most likely a problem with the JsonBird package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     supervisor node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs JsonBird
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls JsonBird
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/JsonBird/npm-debug.log

**Comment by chenyanmo** [comment]
**#cat /opt/JsonBird/npm-debug.log**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@2.15.11
3 info using node@v4.8.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart JsonBird@1.4.0
6 info start JsonBird@1.4.0
7 verbose unsafe-perm in lifecycle true
8 info JsonBird@1.4.0 Failed to exec start script
9 verbose stack Error: JsonBird@1.4.0 start: `supervisor node ./bin/www`
9 verbose stack spawn ENOENT
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:17:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:862:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
10 verbose pkgid JsonBird@1.4.0
11 verbose cwd /opt/JsonBird
12 error Linux 4.4.13-v7+
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
14 error node v4.8.1
15 error npm  v2.15.11
16 error file sh
17 error code ELIFECYCLE
18 error errno ENOENT
19 error syscall spawn
20 error JsonBird@1.4.0 start: `supervisor node ./bin/www`
20 error spawn ENOENT
21 error Failed at the JsonBird@1.4.0 start script 'supervisor node ./bin/www'.
21 error This is most likely a problem with the JsonBird package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     supervisor node ./bin/www
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs JsonBird
21 error Or if that isn't available, you can get their info via:
21 error
21 error     npm owner ls JsonBird
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

**Comment by xCss** [comment]
@chenyanmo 
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

请检查你的`nodejs`版本，`let, const, class`关键字需要高版本支持。

```bash
sh: 1: supervisor: not found

npm ERR! Linux 4.4.13-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.8.1
npm ERR! npm v2.15.11
```
请确认已经`全局安装**supervisor**`。
