### ISSUE TITLE
你好，想知道如何https部署，谢谢

### ISSUE THREAD

**Issue by liyantingcn** [xCss/JsonBird#13]
先感谢提供如此好的工具
最常用的就是HTTP请求转HTTPS，所以需要本地HTTPS部署，请问 如何部署，谢谢

**Comment by xCss** [comment]
参考：
- https://ioliu.cn/2017/add-a-lock-to-your-website/
- https://github.com/Neilpang/acme.sh/wiki/%E8%AF%B4%E6%98%8E
