### ISSUE TITLE
这么好的东西希望能够多推广

### ISSUE THREAD

**Issue by heiyun** [xCss/JsonBird#15]
这么好的东西希望能够多推广,至少我是告诉了身边的朋友们,也希望作者能够不断更新新的功能,完善接口文档,比如自定义header如何使用,希望这个不会停用.

**Comment by xCss** [comment]
@heiyun 暂时不会停用。目前是部署在我自己的服务器上的。
文档后续会更新，目前在考虑升级接口问题。
感谢推广支持。
