### ISSUE TITLE
post接口调用失败问题

### ISSUE THREAD

**Issue by YifengWong** [xCss/JsonBird#17]
使用postman访问http://music.163.com/api/search/pc接口，参数为
('s' = '女儿情');
('offset' = '10');
('limit' = '10');
('type' = '1');
可以得到正确返回结果，但如果使用v2接口post访问http://bird.ioliu.cn/v2/?url=http://music.163.com/api/search/pc会返回
{"msg":"Request method 'GET' not supported","code":400}

请问是bug还是我的使用有问题？

**Comment by xCss** [comment]
@YifengWong 你好，我这边核查了下，发现出现：
```json
{"msg":"Request method 'GET' not supported","code":400}
```
的错误是我程序的bug，会误将链接中带`url参数`的`Post请求`代理成`Get请求`。目前已修复

感谢反馈，祝好~~
