### ISSUE TITLE
对于get请求的header设置

### ISSUE THREAD

**Issue by YifengWong** [xCss/JsonBird#19]
JS无法设置请求头Referer，如果是POST请求的话jsonbird使用params写入headers应该可以绕开这个机制，但是GET请求就没有办法做到了。不知道是否可以增加对此需求的解决方案？

以下是我使用的例子
https://bird.ioliu.cn/v2?url=http://api.xiami.com/web?v=2.0&app_key=1&key=女儿情&page=1&limit=10&r=search/songs
请求头：
"Referer":"http://m.xiami.com/"

使用postman可以顺利完成这个请求，但是在浏览器执行js时就会抛出错误refused to set unsafe header referer

**Comment by xCss** [comment]
@YifengWong 你好，对于`header`的设置，可能是我疏忽了，一开始我就没有想到有可能用`Get`请求方式设置自定义`header`。
我这边先尝试修改下，如果有结果再答复你~
感谢反馈 😃

**Comment by xCss** [comment]
@YifengWong 很抱歉，我这边尝试了多种方法，发现无法获取get的自定义headers。
