### ISSUE TITLE
关于跨域遇到一个问题

### ISSUE THREAD

**Issue by cooliean** [xCss/JsonBird#2]
return axios.get("http://l.fteam.cc/v1/?url=http://uc.365xy.net:8050/blog/list",{})
	return axios.get("https://bird.ioliu.cn/v1?url=http://uc.365xy.net:8050/blog/list",{})

我下了你的项目，运行起来了。配置了一个本地127.0.0.1 的域名  就是l.fteam.cc
但是我的请求就出出现跨域问题，你的域名就不会，是不是服务端，还要配置什么呢，谢谢
下面这个图片是报错信息
<img width="1382" alt="qq20170408-203004 2x" src="https://cloud.githubusercontent.com/assets/4754617/24828902/301d7caa-1c9a-11e7-8c83-b1d595e71099.png">

**Comment by cooliean** [comment]
看来是你网站的技术，我直接请求你的域名都是可以返回html的，但是请求任何其它域名，都是不可以的，不知道这个怎么实现的，谢谢回答。

**Comment by xCss** [comment]
@cooliean 你好，刚从外面回来，抱歉现在才回复你。

你这个是由于缺少跨域配置而造成的跨域问题。
抱歉，我[网站上](https://bird.ioliu.cn)之前因为把跨域配置转到了[Nginx](https://github.com/xCss/nginx/blob/master/includes/cors.template) 。
所以你本地使用会有跨域的问题。

我修改下，然后你再clone试试吧，请稍等。

**Comment by xCss** [comment]
@cooliean 你好，本地跨域代理已经修复，麻烦重新clone一下吧🙂~ 祝好

**Comment by cooliean** [comment]
谢谢，我再试试，咨询一个问题，就是我怎么吧这个项目配置在nginx呢？ 哈哈，对node不是很熟悉，一直都不知道这样的node项目怎么到nginx这样的Web服务上面。

**Comment by xCss** [comment]
@cooliean 你好，我是用的反向代理，有兴趣可以看看我的[Nginx配置](https://github.com/xCss/nginx/blob/master/bird.ioliu.cn.conf)

```nginx
    location / {
        proxy_set_header         X-Real-IP $remote_addr;  
        proxy_set_header         X-Forwarded-For $proxy_add_x_forwarded_for;  
        proxy_set_header         Host $http_host;  
        proxy_set_header         X-NginX-Proxy true;  
        proxy_pass                 http://127.0.0.1:1000/;  
        proxy_redirect             off;  
    }
```

**Comment by cooliean** [comment]
哦哦，明白了。谢谢

**Comment by xCss** [comment]
客气，互帮互助~🙂
