### ISSUE TITLE
歌曲ID有没有一个取值范围？

### ISSUE THREAD

**Issue by zhaoxieluoke** [xCss/JsonBird#3]
如题

**Comment by xCss** [comment]
这个。。。

目前在`网易云音乐`上已听过1w+首歌，表示还没将整个`网易云音乐`上的所有歌曲听完。

而且，我也不知道这个`歌曲ID`的生成规则，so。。。我也不知道这个id的取值范围。

**Comment by zhaoxieluoke** [comment]
这哪能听完，我是想用你的这个接口做一个随机播放的播放器(1w首很吊！)。不过还是谢了，毕竟已经解决了很多问题了
