### ISSUE TITLE
我又来了，网易云那个接口不能跨域了啊 - _ - 

### ISSUE THREAD

**Issue by zhaoxieluoke** [xCss/JsonBird#4]

**Comment by xCss** [comment]
@zhaoxieluoke 很抱歉哦，刚刚看了下，代理网易的接口报错了，暂时还不清楚是什么问题。

手上公司的项目也很急，暂时还没时间修复。

等我找个时间查明原因并修复了，第一时间在这里回复。

**Comment by zhaoxieluoke** [comment]
@xCss 。没事，你先忙你的。多谢多谢[抱拳]

**Comment by Cslove** [comment]
v1代理的接口怎么一下返回400了啊。。？

**Comment by Ryongyon** [comment]
@xCss 网易的接口似乎无法获取单曲mp3地址了，貌似给加密了，无解....不知道大佬能否解决

**Comment by xCss** [comment]
@Cslove v1代理接口我这边没问题，目前只有网易云音乐的接口有点问题。

@Ryongyon 目前正在寻找解决办法，请耐心等待下吧 😄

**Comment by xCss** [comment]
@zhaoxieluoke @Ryongyon 网易云音乐接口已经修复
接口访问方式已变更。
```
**原访问方式**
歌曲接口：https://bird.ioliu.cn/netease?id=222222
歌单接口：https://bird.ioliu.cn/netease?playlist_id=222222
```
**⬇️** 

```
**新访问方式**
歌曲接口：https://bird.ioliu.cn/netease/song?id=222222
歌单接口：https://bird.ioliu.cn/netease/playlist?id=222222
```

**Comment by zhaoxieluoke** [comment]
@xCss 你可算是回来了 ,好的好的
