### ISSUE TITLE
网易云接口貌似又跪了

### ISSUE THREAD

**Issue by zhaoxieluoke** [xCss/JsonBird#8]
status
:
{code: -1, msg: "something happend. Please checked your id or url"}
返回的code都是-1 
- _ -

**Comment by xCss** [comment]
@zhaoxieluoke 我这边访问是正常的：
https://bird.ioliu.cn/netease/song?id=222222
![1](https://user-images.githubusercontent.com/10877162/27716436-f6748a6c-5d70-11e7-927b-de7bcf525474.png)

https://bird.ioliu.cn/netease/playlist?id=222222
![2](https://user-images.githubusercontent.com/10877162/27716444-04a3db74-5d71-11e7-8ba1-af24739bf29d.png)

**Comment by zhaoxieluoke** [comment]
@xCss  我的天,居然好了

**Comment by Ryongyon** [comment]
@xCss 为什么我这里显示504 Gateway Time-out？

**Comment by xCss** [comment]
@Ryongyon 我重启了服务，还是一样的出现504.

但是在我本地测试却不会出现这个问题。。。

正在排查原因....

**Comment by xCss** [comment]
@Ryongyon @zhaoxieluoke 目测是因为请求太频繁，被网易云ban了，正在寻找解决办法。。。

**Comment by zhaoxieluoke** [comment]
@xCss, 我的请求是小水管

**Comment by xCss** [comment]
@zhaoxieluoke @Ryongyon 目前网易云音乐接口已经恢复

**Comment by zhaoxieluoke** [comment]
@xCss  thanks again
