### ISSUE TITLE
请求头带的数据信息无法传递到后台

### ISSUE THREAD

**Issue by panhuibingithub** [xCss/JsonBird#9]
使用https://bird.ioliu.cn/v1?url=http://stg3-web.itp-live.pingan.com.cn:13080/live/sdk/entryLiveRoom.do
发现ajax 请求头内带的附加的信息
Connection:keep-alive
Content-Length:18
content-type:application/x-www-form-urlencoded;charset=UTF-8
device:4
Host:bird.ioliu.cn
imei:
nonce:50
Origin:http://1035291532.appservice.open.weixin.qq.com
Pragma:no-cache
Referer:https://servicewechat.com/wx34eff525599bcf25/devtools/page-frame.html
sign:228e9d7dad144cc6338cfc6e98ef8e8b876dc025
timestamp:1498733930
token:dBtTBYF2NShs0eXKOoIrmCrrHz3Xqmyt014FoMfHID6/CzxSCT0+17aNJ62ZMxPd3moW75motfqXSPjRjHhyKA==
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 appservice webview/100000
version:2
X-Requested-With:XMLHttpRequest
无法传递过去，后台无法获取到

**Comment by xCss** [comment]
@panhuibingithub 目前新增v2接口，可以传输自定义header头。
